import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    rjsf: 'src/components/rjsf/index.ts',
  },
  format: ['cjs'],
  dts: true,
  splitting: false,
  clean: true,
  treeshake: true,
  sourcemap: true,
  target: 'es2022',
  outDir: 'dist',
  external: [
    '@legendapp/list',
    '@lichens-innovation/ts-common',
    '@noble/hashes',
    '@uidotdev/usehooks',
    'buffer',
    'date-fns',
    'date-fns-tz',
    'fast-xml-parser',
    'filesize',
    'handlebars',
    'immer',
    'mobx',
    'mobx-persist-store',
    'mobx-react-lite',
    'react-hook-form',
    'react-syntax-highlighter',
    '@gorhom/bottom-sheet',
    '@react-native-clipboard/clipboard',
    '@react-native-community/datetimepicker',
    '@react-native-community/netinfo',
    '@react-native-community/slider',
    '@react-navigation/native',
    '@rjsf/core',
    '@rjsf/utils',
    '@rjsf/validator-ajv8',
    '@sentry/react-native',
    '@tanstack/react-query',
    'ajv-i18n',
    'axios',
    'expo',
    'expo-application',
    'expo-asset',
    'expo-build-properties',
    'expo-camera',
    'expo-constants',
    'expo-dev-client',
    'expo-device',
    'expo-document-picker',
    'expo-file-system',
    'expo-font',
    'expo-image-picker',
    'expo-linking',
    'expo-localization',
    'expo-location',
    'expo-router',
    'expo-secure-store',
    'expo-sharing',
    'expo-speech-recognition',
    'expo-splash-screen',
    'expo-sqlite',
    'expo-status-bar',
    'expo-updates',
    'i18next',
    'react',
    'react-dom',
    'react-i18next',
    'react-native',
    'react-native-element-dropdown',
    'react-native-gesture-handler',
    'react-native-logs',
    'react-native-mmkv',
    'react-native-paper',
    'react-native-reanimated',
    'react-native-safe-area-context',
    'react-native-screens',
    'react-native-svg',
    'react-native-syntax-highlighter',
    'react-native-uuid',
    'react-native-vector-icons',
    'react-native-web',
    'react-native-webview',
    'react-native-wifi-reborn',
    'react-native-winrt',
    'react-native-zeroconf',
  ],
});
