import type { ThemeProps } from '@rjsf/core';
import { RjsfPaperFormWrapper } from './form-submit-context';
import {
  CheckboxWidget,
  CheckboxesWidget,
  DateTimeWidget,
  DateWidget,
  HiddenWidget,
  ImageVideoGalleryWidget,
  NumberWidget,
  PasswordWidget,
  RadioWidget,
  RadioYesNoWidget,
  RangeWidget,
  SelectWidget,
  TextWidget,
  TextareaWidget,
  LabelWidget,
} from './widgets';
import { TextWithVoiceRecordingField } from './fields';

export const RJSF_PAPER_THEME: ThemeProps = {
  widgets: {
    TextWidget,
    TextareaWidget,
    HiddenWidget,
    password: PasswordWidget,
    PasswordWidget,
    date: DateWidget,
    DateWidget,
    datetime: DateTimeWidget,
    DateTimeWidget,
    select: SelectWidget,
    SelectWidget,
    radio: RadioWidget,
    RadioWidget,
    range: RangeWidget,
    RangeWidget,
    radioYesNo: RadioYesNoWidget,
    RadioYesNoWidget,
    number: NumberWidget,
    updown: NumberWidget,
    NumberWidget,
    UpDownWidget: NumberWidget,
    checkbox: CheckboxWidget,
    CheckboxWidget,
    checkboxes: CheckboxesWidget,
    CheckboxesWidget,
    imageVideoGallery: ImageVideoGalleryWidget,
    ImageVideoGalleryWidget,
    label: LabelWidget,
    LabelWidget,
  },
  fields: {
    TextWithVoiceRecordingField,
  },
  _internalFormWrapper: RjsfPaperFormWrapper as ThemeProps['_internalFormWrapper'],
};
